Vagrant.configure("2") do |config|
  config.vm.box = "devopsguys/Windows2012R2Eval"
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 5985, host: 5986
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision :shell, path: "shell/main.cmd"
  config.vm.provision :shell, path: "shell/InstallChocoPackages.bat"
end