
Vagrant.configure(2) do |config|
  config.vm.box =  "nitaco/xenial64-ansible"
  config.vm.network "private_network", ip: "172.28.128.5"
  config.vm.network "forwarded_port", guest: 5985, host: 5986 # WinRM
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Jenkins
end